config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :finishers, only: [:index]
  resources :reports, only: [:index, :show]
  get 'gallery' => "gallery#index"
  get 'register' => "register#new"
  post 'apply' => "register#create", as: :apply_form 
  match ":url" => 'pages#show', via: :get

  root "pages#home"
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/finisher.rb
class Finisher < ActiveRecord::Base
  has_many :starts
  mount_uploader :photo, PhotoUploader

  def name
    self.first_name + ' ' + self.last_name
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :start
  mount_uploader :file, FileUploader
end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :start
  paginates_per 5
  mount_uploader :cover_image, CoverImageUploader
end

app/models/request.rb
class Request < ActiveRecord::Base
  validates_presence_of :name
  validates_presence_of :contact_info
  validates_presence_of :kind
end

app/models/start.rb
class Start < ActiveRecord::Base
  belongs_to :finisher
  has_many :images
  has_many :reports
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/finishers_controller.rb
class FinishersController < ApplicationController
  def index
    @finishers = Finisher.all.order(updated_at: :desc)
  end
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  def index
    @images = Image.all.order(created_at: :desc)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    @page = Page.find_by(url: params[:url])
  end

  def home
  end
end

app/controllers/register_controller.rb
class RegisterController < ApplicationController
  def new
    @request = Request.new
  end

  def create
    req = Request.create(request_params)
    if req
      notice = "Заявка принята и будет обработана в ближайшее время. Спасибо"
    end
    redirect_to :back, notice: notice
  end

  private def request_params
    params.require(:request).permit(:name, :age, :when, :country, :city, :contact_info, :comment, :kind)
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.order(date: :desc).page params[:page]
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @report = Report.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/finishers_helper.rb
module FinishersHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/finishers/index.html.erb
<section class="shortcode-item">
  <div class="container">
    <div class="row">
      <div class="center">  
          <h2>Финишеры 2014-2015гг</h2>
      </div>
      <table class="table table-striped table-bordered table-hover " width="100%">
        <thead>

          <tr>
            <th>#</th>
            <th>Имя пловца </th>
            <th>Город</th>
            <th>Страна</th>
            <th>Полных лет на м. заплыва</th>
            <th>Пол</th>
            <th>Гидрокостюм/без</th>
            <th>Дата заплыва</th>
            <th>Время</th>
            <th>Тип</th>
          </tr>
        </thead>
        <tbody>
          <% @finishers.each_with_index do |fin, index| %>
            <% fin.starts.each do |start| %>
              <tr>
                <td><%= index+1 %></td>
                <td><%= fin.first_name %> <%= fin.middle_name %> <%= fin.last_name %></td>
                <td><%= fin.city %></td>
                <td><%= fin.country %></td>
                <td><%= fin.age %></td>
                <td><%= fin.gender %></td>
                <td><%= start.wetsuit ? 'Wetsuit' : 'Non-wetsuit' %></td>
                <td><%= start.date %></td>
                <td><%= start.time %></td>
                <td><%= start.kind %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>
<section id="bottom">
  <div class="container">
    <div class="row">
  Текст про то как классно плавать, зарегайся сегодня
    </div>
  </div>
</section>

app/views/gallery/index.html.erb
<section id="blog" class="container">
  <div class="container">
    <div class="center">
       <h2>Фотогалерея</h2>
    </div>
    <div class="row">
      <% @images.each do |image| %>
        <div class="portfolio-item apps col-xs-12 col-sm-4 col-md-3">
          <div class="recent-work-wrap">
            <%=image_tag image.file.thumb.url, class: "img-responsive" %>
            <div class="overlay">
              <%=link_to image.file.url, class: "preview", rel: "prettyPhoto" do %>
                <div class="recent-work-inner" style="padding: 50px;">
                  <i class="fa fa-eye"></i> увеличить
                </div> 
              <% end %>
            </div>
          </div>
        </div><!--/.portfolio-item-->
      <% end %>

    </div>
  </div>
</section>
<section id="bottom">
  <div class="container">
    <div class="row">
      А еще текст про то, как отдохнуть в СПБ
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Kotlinrace</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <base href="/" />    
      <!-- core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/font-awesome.min.css" rel="stylesheet">
    <link href="css/animate.min.css" rel="stylesheet">
    <link href="css/prettyPhoto.css" rel="stylesheet">
    <link href="css/main.css" rel="stylesheet">
    <link href="css/responsive.css" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->       
    <link rel="shortcut icon" href="images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="images/ico/apple-touch-icon-57-precomposed.png">
  <!-- Yandex.Metrika counter --><script type="text/javascript">(function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter30658127 = new Ya.Metrika({id:30658127, clickmap:true, trackLinks:true, accurateTrackBounce:true}); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks");</script><noscript><div><img src="//mc.yandex.ru/watch/30658127" style="position:absolute; left:-9999px;" alt="" /></div></noscript><!-- /Yandex.Metrika counter -->
    
  </head>
  <body>
    
    <header id="header">
        <!-- Fixed navbar -->
        <div class="navbar navbar-inverse" role="banner">
            <div class="logotype"><a href="/"><img src="img/kotlinrace.png" width=
            "180px"></a></div>
            <div class="container">
                <div class="navbar-header">
                    <!-- Button for smallest screens --> <button class=
                    "navbar-toggle collapsed" data-target=".navbar-collapse"
                    data-toggle="collapse" type="button"><span class=
                    "sr-only">Переключиться</span> <span class=
                    "icon-bar"></span> <span class="icon-bar"></span>
                    <span class="icon-bar"></span></button>
                </div>
                <div class="navbar-collapse collapse" style="height: 0px;">
                    <ul class="nav navbar-nav pull-right">
                        <li>
                            <a class="ember-view" href="/finishers" >Финишеры</a>
                        </li>
                        <li>
                            <a class="ember-view" href="/gallery" >Фото</a>
                        </li>
                        <li>
                            <a class="ember-view" href="/reports" >Отчеты</a>
                        </li>
                        <li>
                            <a class="ember-view" href="/culture" >Культура</a>
                        </li>
                        
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown"
                            href="#">О заплыве<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="ember-view" href="/about" >О заплыве</a>
                                </li>
                                <li>
                                    <a class="ember-view" href="/history">История</a>
                                </li>
                                <li>
                                    <a class="ember-view" href="/rules">Правила</a>
                                </li>
                                <li>
                                    <a class="ember-view" href="/authors">Об организаторах</a>
                                </li>
                            </ul>
                        </li>
                        <li class="active">
                            <a class="btn ember-view" href="/register">Зарегистрироваться</a>
                        </li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </div><!-- /.navbar -->
    </header>
    <%=yield %>
    <footer class="midnight-blue" id="footer">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    © 2014-2016 Kotlinrace
                </div>
                <div class="col-sm-6">
                    <ul class="pull-right">
                        <li>
                            <a class="ember-view active" href="/" id=
                            "ember478">Главная</a>
                        </li>
                        <li>
                            <a class="ember-view" href="/about" id=
                            "ember479">О заплыве</a>
                        </li>
                        <li>
                            <a class="btn ember-view" href="/register" id=
                            "ember480">Зарегистрироваться</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer><!--/#footer-->

    <script src="js/jquery.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/jquery.prettyPhoto.js"></script>
    <script src="js/jquery.isotope.min.js"></script>
    <script src="js/main.js"></script>
    <script src="js/wow.min.js"></script>    
  </body>
</html>

app/views/pages/home.html.erb
<section class="no-margin" id="main-slider">
    <div class="carousel slide">
        <ol class="carousel-indicators">
            <li class="active" data-slide-to="0" data-target=
            "#main-slider"></li>
            <li data-slide-to="1" data-target="#main-slider"></li>
            <li data-slide-to="2" data-target="#main-slider"></li>
        </ol>
        <div class="carousel-inner">
            <div class="item active" style=
            "background-image: url(images/slider/bg1.jpg)">
                <div class="container">
                    <div class="row slide-margin">
                        <div class="col-sm-6">
                            <div class="carousel-content">
                                <h1 class="animation animated-item-1"
                                style="text-shadow: 1px 1px 2px grey;">
                                От Питера до Кронштадта</h1>
                                <h2 class="animation animated-item-2"
                                style="text-shadow: 1px 1px 2px grey;">
                                Преодолей себя в заплыве на
                                25км</h2><a class=
                                "btn-slide animation animated-item-3 ember-view"
                                href="/about" id="ember613">Вызов
                                принят!</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!--/.item-->
            <div class="item" style=
            "background-image: url(images/slider/bg3.jpg)">
                <div class="container">
                    <div class="row slide-margin">
                        <div class="col-sm-6">
                            <div class="carousel-content">
                                <h1 class="animation animated-item-1"
                                style="text-shadow: 1px 1px 2px grey;">
                                Соло или эстафета?</h1>
                                <h2 class="animation animated-item-2"
                                style="text-shadow: 1px 1px 2px grey;">
                                Проплыви сам или со своей
                                командой</h2><a class=
                                "btn-slide animation animated-item-3 ember-view"
                                href="/rules" id="ember614">Правила
                                участия...</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!--/.item-->
            <div class="item" style=
            "background-image: url(images/slider/bg2.jpg)">
                <div class="container">
                    <div class="row slide-margin">
                        <div class="col-sm-6">
                            <div class="carousel-content">
                                <h1 class="animation animated-item-1"
                                style="text-shadow: 1px 1px 2px grey;">
                                Участвуй в Kotlinrace 2016</h1>
                                <h2 class="animation animated-item-2"
                                style="text-shadow: 1px 1px 2px grey;">
                                Выбрать дату участия и оставь
                                заявку</h2><a class=
                                "btn-slide animation animated-item-3 ember-view"
                                href="/register" id=
                                "ember615">Регистрация...</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!--/.item-->
        </div><!--/.carousel-inner-->
    </div><!--/.carousel--> <a class="prev hidden-xs" data-slide="prev"
    href="#main-slider"><i class="fa fa-chevron-left"></i></a>
    <a class="next hidden-xs" data-slide="next" href=
    "#main-slider"><i class="fa fa-chevron-right"></i></a>
</section><!--/#main-slider-->

app/views/pages/show.html.erb
<%=h @page.content %>

app/views/register/new.html.erb
<section id="blog" class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div id="contact-page clearfix">
          <% if flash[:notice] %>
            <div class="status alert alert-success">
              <%= flash[:notice] %>
            </div>
          <% end %>
          <div class="message_heading">
              <h2>Форма отравки заявки на участие</h2>
              <p>Убедитесь что все обязательные поля (помечены *) заполнены.</p>
          </div> 
          <form id="main-contact-form" class="contact-form" name="contact-form" method="post" action="<%=apply_form_path %>" role="form">
             <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
              <div class="row">
                <div class="col-sm-5">
                  <div class="form-group">
                    <label>Ваше имя *</label>
                    <input type="text" class="form-control" name="request[name]"required="required" placeholder="пример: Дмитрий Иванович Пловцов">
                  </div>
                  <div class="form-group">
                    <label>Предполагаемая дата заплыва *</label>
                    <input type="text" class="form-control" name="request[when]"required="required" placeholder="пример: летом 2016 / конец июля / 28-08-2016">
                  </div>
                  <div class="form-group">
                    <label>Возраст *</label>
                    <input type="text" class="form-control" name="request[age]"required="required">
                  </div>
                  <div class="form-group">
                    <label>Страна</label>
                    <input type="text" class="form-control" name="request[country]">
                  </div>

                </div>
                <div class="col-sm-7">
                  <div class="form-group">
                    <label>Контакт (телефон/email) *</label>
                    <input type="text" class="form-control" name="request[contact_info]"required="required" placeholder="пример: +79211231223, marathoner@kotlinrace.ru">
                  </div>
                  <div class="form-group">
                    <label>Тип гонки</label>
                    <select class="form-control" name="request[kind]" required="required">
                      <option disabled selected value> -- Выбрать -- </option>
                      <option value="solo">Сольный заплыв</option>
                      <option value="relay">Эстафета</option>
                    </select>
                  </div>

                  <div class="form-group">
                    <label>Вопрос/комментарий к организаторам (если есть)</label>
                    <textarea name="request[comment]" id="message" class="form-control" rows="4"></textarea>
                  </div>                        
                  <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-lg" required="required">Отправить заявку</button>
                  </div>
                </div>
              </div>
          </form>     
      </div><!--/#contact-page-->
    </div>
  </div>

</section>
<style>
  body {
    background: #fff url(/images/3.jpg);
    z-index: -1;
    color: #fff !important;
  }
  h2 {
    color: #fff;
  }
</style>

app/views/reports/index.html.erb
<section id="blog" class="container">
  <div class="center">
    <h2>Отчеты участников</h2>
  </div>

  <div class="blog">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <% @reports.each do |report| %>
          <div class="blog-item">
            <div class="row">
              <div class="col-xs-12 col-sm-2 text-center">
                <div class="entry-meta">
                  <span id="publish_date"><%=report.date %></span>
                  <span><i class="fa fa-user"></i> <a href="#"><%=report.author %></a></span>
                </div>
              </div>
                  
              <div class="col-xs-12 col-sm-10 blog-content">
                <%=link_to (image_tag report.cover_image.scaled.url, class: "img-responsive img-blog"), report %>
                <h2><%=link_to report.title, report %></h2>
                <h3><%=report.description %></h3>
                <%=link_to report, class: "btn btn-primary readmore" do %>
                  Далее...
                <% end %>
              </div>
            </div>    
          </div><!--/.blog-item-->
        <% end %>
        <%=paginate @reports %>
      </div><!--/.col-md-8-->

    </div><!--/.row-->
  </div>
</section><!--/#blog-->

<section id="bottom">

</section><!--/#bottom-->

app/views/reports/show.html.erb
<section id="blog" class="container">
  <div class="blog">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="blog-item">
          <%=image_tag @report.cover_image.scaled.url, class: "img-responsive img-blog", width: '100%'%>
              <div class="row">  
                  <div class="col-xs-12 col-sm-2 text-center">
                    <div class="entry-meta">
                      <span id="publish_date"><%=@report.date%></span>
                      <span><i class="fa fa-user"></i> <%=@report.author%></span>
                    </div>
                  </div>
                  <div class="col-xs-12 col-sm-10 blog-content">
                      <h2><%=@report.title %></h2>
                      <p><%=@report.description %></p>
                      <p>
                        <%=raw @report.body %>
                      </p>

                  </div>
              </div>
            </div><!--/.blog-item-->
            
            <div class="media reply_section">
                <div class="pull-left post_reply text-center">
                  Поделитесь с друзьями
                </div>
                <div class="media-body post_reply_content">
                    <script type="text/javascript">(function() {
  if (window.pluso)if (typeof window.pluso.start == "function") return;
  if (window.ifpluso==undefined) { window.ifpluso = 1;
    var d = document, s = d.createElement('script'), g = 'getElementsByTagName';
    s.type = 'text/javascript'; s.charset='UTF-8'; s.async = true;
    s.src = ('https:' == window.location.protocol ? 'https' : 'http')  + '://share.pluso.ru/pluso-like.js';
    var h=d[g]('body')[0];
    h.appendChild(s);
  }})();</script>
<div class="pluso" data-background="#ebebeb" data-options="big,square,line,horizontal,counter,theme=04" data-services="vkontakte,facebook,twitter" data-url="http://kotlinrace.ru/<%=report_path(@report)%>" data-title="<%= @report.title %>" data-description="<%=@report.description %>"></div>
                </div>
            </div> 
            
        </div><!--/.col-md-8-->
    </div><!--/.row-->
  </div><!--/.blog-->
</section><!--/#blog-->